/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingGalleryRouteImport } from './routes/wedding-gallery'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreWeddingGalleryRouteImport } from './routes/pre-wedding-gallery'
import { Route as PortraitGalleryRouteImport } from './routes/portrait-gallery'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FashionGalleryRouteImport } from './routes/fashion-gallery'
import { Route as EventGalleryRouteImport } from './routes/event-gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CinematicGalleryRouteImport } from './routes/cinematic-gallery'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeddingGalleryRoute = WeddingGalleryRouteImport.update({
  id: '/wedding-gallery',
  path: '/wedding-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreWeddingGalleryRoute = PreWeddingGalleryRouteImport.update({
  id: '/pre-wedding-gallery',
  path: '/pre-wedding-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitGalleryRoute = PortraitGalleryRouteImport.update({
  id: '/portrait-gallery',
  path: '/portrait-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionGalleryRoute = FashionGalleryRouteImport.update({
  id: '/fashion-gallery',
  path: '/fashion-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventGalleryRoute = EventGalleryRouteImport.update({
  id: '/event-gallery',
  path: '/event-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicGalleryRoute = CinematicGalleryRouteImport.update({
  id: '/cinematic-gallery',
  path: '/cinematic-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic-gallery': typeof CinematicGalleryRoute
  '/contact': typeof ContactRoute
  '/event-gallery': typeof EventGalleryRoute
  '/fashion-gallery': typeof FashionGalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/portrait-gallery': typeof PortraitGalleryRoute
  '/pre-wedding-gallery': typeof PreWeddingGalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic-gallery': typeof CinematicGalleryRoute
  '/contact': typeof ContactRoute
  '/event-gallery': typeof EventGalleryRoute
  '/fashion-gallery': typeof FashionGalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/portrait-gallery': typeof PortraitGalleryRoute
  '/pre-wedding-gallery': typeof PreWeddingGalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic-gallery': typeof CinematicGalleryRoute
  '/contact': typeof ContactRoute
  '/event-gallery': typeof EventGalleryRoute
  '/fashion-gallery': typeof FashionGalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/portrait-gallery': typeof PortraitGalleryRoute
  '/pre-wedding-gallery': typeof PreWeddingGalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cinematic-gallery'
    | '/contact'
    | '/event-gallery'
    | '/fashion-gallery'
    | '/portfolio'
    | '/portrait-gallery'
    | '/pre-wedding-gallery'
    | '/sitemap.xml'
    | '/wedding-gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cinematic-gallery'
    | '/contact'
    | '/event-gallery'
    | '/fashion-gallery'
    | '/portfolio'
    | '/portrait-gallery'
    | '/pre-wedding-gallery'
    | '/sitemap.xml'
    | '/wedding-gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cinematic-gallery'
    | '/contact'
    | '/event-gallery'
    | '/fashion-gallery'
    | '/portfolio'
    | '/portrait-gallery'
    | '/pre-wedding-gallery'
    | '/sitemap.xml'
    | '/wedding-gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CinematicGalleryRoute: typeof CinematicGalleryRoute
  ContactRoute: typeof ContactRoute
  EventGalleryRoute: typeof EventGalleryRoute
  FashionGalleryRoute: typeof FashionGalleryRoute
  PortfolioRoute: typeof PortfolioRoute
  PortraitGalleryRoute: typeof PortraitGalleryRoute
  PreWeddingGalleryRoute: typeof PreWeddingGalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingGalleryRoute: typeof WeddingGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-gallery': {
      id: '/wedding-gallery'
      path: '/wedding-gallery'
      fullPath: '/wedding-gallery'
      preLoaderRoute: typeof WeddingGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-wedding-gallery': {
      id: '/pre-wedding-gallery'
      path: '/pre-wedding-gallery'
      fullPath: '/pre-wedding-gallery'
      preLoaderRoute: typeof PreWeddingGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portrait-gallery': {
      id: '/portrait-gallery'
      path: '/portrait-gallery'
      fullPath: '/portrait-gallery'
      preLoaderRoute: typeof PortraitGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion-gallery': {
      id: '/fashion-gallery'
      path: '/fashion-gallery'
      fullPath: '/fashion-gallery'
      preLoaderRoute: typeof FashionGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-gallery': {
      id: '/event-gallery'
      path: '/event-gallery'
      fullPath: '/event-gallery'
      preLoaderRoute: typeof EventGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematic-gallery': {
      id: '/cinematic-gallery'
      path: '/cinematic-gallery'
      fullPath: '/cinematic-gallery'
      preLoaderRoute: typeof CinematicGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CinematicGalleryRoute: CinematicGalleryRoute,
  ContactRoute: ContactRoute,
  EventGalleryRoute: EventGalleryRoute,
  FashionGalleryRoute: FashionGalleryRoute,
  PortfolioRoute: PortfolioRoute,
  PortraitGalleryRoute: PortraitGalleryRoute,
  PreWeddingGalleryRoute: PreWeddingGalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingGalleryRoute: WeddingGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
